services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - skybooker-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
 
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - skybooker-network
    healthcheck:
      test: ["CMD-SHELL", "/bin/bash -c 'for i in {1..10}; do /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"YourStrong!Passw0rd\" -Q \"SELECT 1\" -b -o /dev/null && exit 0 || sleep 5; done; exit 1'"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 60s
    restart: on-failure
    mem_limit: 2g
 
  flight-service:
    build:
      context: .
      dockerfile: FlightService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - FlightDatabaseSettings__ConnectionString=mongodb://mongodb:27017
      - FlightDatabaseSettings__DatabaseName=FlightDb
      - FlightDatabaseSettings__FlightCollectionName=flights
    depends_on:
      - db
    networks:
      - skybooker-network
 
  booking-service:
    build:
      context: .
      dockerfile: BookingService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BookingDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - skybooker-network
    restart: on-failure
 
  auth-service:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=AuthDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - skybooker-network
    restart: on-failure
 
networks:
  skybooker-network:
    driver: bridge
 
volumes:
  mongodb_data:
  sqldata: